### ISSUE TITLE
@shared_task() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by vkgautham** [maciej-gol/tenant-schemas-celery#130]
TypeError at .../
**my_shared_task() takes 0 positional arguments but 1 was given**

Celery shared_task doesn't take any positional arguments, but the example in documentation binds TenantTask for shared tasks  which throws exception.

```
   from celery import shared_task
   from django.db import connection
   from myproject.celery import app
   from tenant_schemas_celery.task import TenantTask

   @app.task
   def my_task():
      print(connection.schema_name)

   @shared_task(base=TenantTask, bind=True)
   def my_shared_task():
      print("foo")
```

Any idea?

**Comment by maciej-gol** [comment]
What's your celery version? It works correctly on `5.4.0` (in tests).

**Comment by vkgautham** [comment]
Just "celery" in requirements.txt (Docker) didnt pick up the latest version. Need to explicit version. 

Thanks
