### ISSUE TITLE
Task headers are None when using Task.retry()

### ISSUE THREAD

**Issue by alexjillard** [maciej-gol/tenant-schemas-celery#14]
When using Task.retry( ) with the `fix_missing_headers` branch (Issue #12) the `headers` key in the kwargs is None.

This causes `self._add_current_schema(kw.setdefault('headers', {}))` in https://github.com/maciej-gol/tenant-schemas-celery/blob/fix_missing_headers/tenant_schemas_celery/task.py#L22 to return None rather than an empty dict.

https://github.com/maciej-gol/tenant-schemas-celery/blob/fix_missing_headers/tenant_schemas_celery/task.py#L13 will the Throw `AttributeError: 'NoneType' object has no attribute 'setdefault'` 

We're using Celery 4.0.2 with redis and https://github.com/maciej-gol/tenant-schemas-celery/tree/fix_missing_headers.

I've opened PR #13 that has some small changes to make sure  that headers is a dict before attempting to add the schema name to it.

**Comment by maciej-gol** [comment]
Thanks a lot! I'll push the new version with these fixes tomorrow.
