### ISSUE TITLE
Logging to have schema_name 

### ISSUE THREAD

**Issue by thelinuxer** [maciej-gol/tenant-schemas-celery#17]
Hi,
django-tenant-schemas application has a configuration to have the schema name in each log message. This allows us to know which request is handled for whom.

I can't seem to understand how the same can be achieved with celery logging using your application. 

Can you please provide more insight on that ?

**Comment by maciej-gol** [comment]
Could you point me to the settings name in `django-tenants-schemas`? I didn't keep up with the project recently.

**Comment by thelinuxer** [comment]
I can't find the link right now, but here is LOGGING section in settings.py:

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        },
        'tenant_filter': {
            '()': 'tenant_schemas.log.TenantContextFilter'
        },
    },
    'formatters': {
        'tenant_format': {
            'format': '[%(schema_name)s %(levelname)-7s]'
            ' %(message)s',
        },
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['tenant_filter'],
            'formatter': 'tenant_format',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'gunicorn.access': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'gunicorn.error': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
    }
}
```

**Comment by thelinuxer** [comment]
Found it, it was a more basic version of what I have right now.

http://django-tenant-schemas.readthedocs.io/en/latest/use.html#logging

**Comment by maciej-gol** [comment]
How do you access the logger? It is important as the filters' usage depends on which logger is being used (logger's name).

**Comment by thelinuxer** [comment]
In celery the normal way to access logging is the following as far as I know:
```
from celery.utils.log import get_logger
logger = get_logger(__name__)
```

**Comment by maciej-gol** [comment]
Have you then tried to attach the filter to the root logger, or the logger that is the root of your app package?

**Comment by thelinuxer** [comment]
I will look it up since I am a bit inexperienced with python logging.

**Comment by maciej-gol** [comment]
Basically, if your django app is placed under a common package you can attach the filter to that package's logger. For exampl,e all your django apps are within a `my_app` package: `myapp.main.views`, `myapp.crawler.models`, `myapp.slack_integration.models`, `myapp.accounts.tasks`, etc. In this case the logger that you can use would be `myapp`. This is how logging hierarchy works.

**Comment by maciej-gol** [comment]
@thelinuxer did you manage to figure this out?
