### ISSUE TITLE
How to use celery beat with all tenants

### ISSUE THREAD

**Issue by jlariza** [maciej-gol/tenant-schemas-celery#18]
Good day,

I am setting up an application with django-tenants and tenants-schemas-celery

I have a question. I need to run a periodic task with celery beat on all the schemas.

Following the example, I have

```
app.conf.beat_schedule = {
    'test': {
        'task': 'myapp.tasks.print_schema',
        'schedule': 10,
    }
}
```
but when I run it, i only see the public schema being print every ten seconds. What I am missing?
myapp is a tenant app (inside TENANT_APPS). I am using tenant-schemas-celery 0.1.7 and celery 4.1.0

Thank you,

**Comment by maciej-gol** [comment]
If you want to run a scheduled task for all tenants, you need two tasks:
the scheduled one and the one with logic. The scheduled task would iterate
over all tenants and activate them and send the task with logic. The second
task should automatically have the schema set to the schema of the tenant
that was active when sending it.

1 lis 2017 00:46 "jlariza" <notifications@github.com> napisał(a):

**Comment by jlariza** [comment]
Thank you.  @maciej-gol 

I could make it work with the following code.

```
@app.task
def print_schema_name():
    print(connection.schema_name)

@app.task
def print_schema():
    tenants = Client.objects.all()
    for tenant in tenants:
        connection.set_tenant(tenant)
        print_schema_name()
```

**Comment by maciej-gol** [comment]
Closing since this has got resolved ;-)
