### ISSUE TITLE
Won't work with Django-tenants

### ISSUE THREAD

**Issue by tomturner** [maciej-gol/tenant-schemas-celery#21]
see https://github.com/tomturner/django-tenants/issues/184

**Comment by maciej-gol** [comment]
Have to add both libraries to travis matrix! Thanks! I need to fix the
tests setup first, since celery killed eager mode during tests :C

pt., 5 paź 2018 o 22:33 Tom Turner <notifications@github.com> napisał(a):

**Comment by maciej-gol** [comment]
Is it enough to remove `django-tenant-schemas` from the explicit dependencies?

**Comment by tomturner** [comment]
I believe you should be able to remove that line

**Comment by maciej-gol** [comment]
It's already been removed on `master`. I guess we can close this issue, then.

**Comment by maciej-gol** [comment]
I will release a new version tomorrow.

**Comment by maciej-gol** [comment]
Fixed in `0.2.0`.
