### ISSUE TITLE
Django 2 with multi tenancy

### ISSUE THREAD

**Issue by anoopjohn-inapp** [maciej-gol/tenant-schemas-celery#26]
I've been using django-tenant-schemas with django 2.1.7, django-tenant-schemas==1.9.0.
 Will tenant-schemas-celery support as I've used celery==4.3.0

**Comment by maciej-gol** [comment]
Afaik, the Travis Ci build for django 2.2.1, celery 4.3.0 and
django-tenant-schemas 1.9.0 works, so the library should work, too. Will
check today.

pon., 6 maj 2019, 07:48 użytkownik anoopjohn-inapp <notifications@github.com>
napisał:

**Comment by anoopjohn-inapp** [comment]
Thanks  maciej-gol

**Comment by maciej-gol** [comment]
The tests are passing on ```$ pip freeze
amqp==2.4.2
atomicwrites==1.2.1
attrs==18.2.0
billiard==3.6.0.0
celery==4.3.0
Click==7.0
Django==2.1.7
django-tenant-schemas==1.9.0
kombu==4.5.0
more-itertools==4.3.0
pip-tools==3.1.0
pluggy==0.7.1
psycopg2==2.8.2
py==1.6.0
pytest==3.8.2
pytest-django==3.4.3
pytz==2019.1
six==1.11.0
-e git+git@github.com:maciej-gol/tenant-schemas-celery.git@277ad98a756826d0fe311b9be6870988de3cd661#egg=tenant_schemas_celery
vine==1.3.0
```
so I guess it should work for you, too.

**Comment by anoopjohn-inapp** [comment]
Thanks maciej-gol. Glad for your quick response.

**Comment by maciej-gol** [comment]
Closing as there was so far no issue with django 2 reported.
