### ISSUE TITLE
Support for celery-beat

### ISSUE THREAD

**Issue by mcroni** [maciej-gol/tenant-schemas-celery#27]
using this package with django tenants which works without a problem ,wondering if it can work with django_celery_beat too

**Comment by maciej-gol** [comment]
How would you want the integration to look like?

**Comment by mcroni** [comment]
i didnt use django_celery_beat, i went with implementing celerybeat with the app.conf setup, thanks but the issue im currently facing is this 
`ExecStart=/bin/sh -c '${CELERY_BIN} multi start ${CELERYD_NODES} \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS}'`
i have this in my sytemd daemon file but when i run a `.delay()` it doesn't get picked up. running two workers with the name `worker1 ` `worker2`

**Comment by b1tst0rm** [comment]
Just wanted to chime in to say that I have the same issue, Celery Beat-initiated tasks are sent according to the logs but never executed by Celery when using this package.

**Comment by maciej-gol** [comment]
@b1tst0rm could you please give an example of your task? AFAIK, this package should not fiddle with how tasks are sent to the queue other than adding one keyword argument.

**Comment by b1tst0rm** [comment]
I think the issue lies in the fact that the default Celery Beat scheduler sits in the public schema issuing tasks. It is not aware that it needs to iterate through each available tenant schema, therefore the tasks never really get executed for the tenants.

I will look into this some more after work today when I have time.

An example of my task is below. It simply runs every night at 2am to clear out a "notification" model instance that has been read awhile ago. 

Celery.py:
```
from __future__ import absolute_import, unicode_literals
import os
from django.conf import settings
from celery import Celery
from celery.schedules import crontab
from tenant_schemas_celery.app import CeleryApp

# set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'trackpdsite.settings')

if settings.ENABLE_MULTITENANT:
    app = CeleryApp("<myproject>")
else:
    app = Celery("<myproject>")

app.config_from_object('django.conf:settings', namespace='CELERY')

# Load task modules from all registered Django app configs.
app.autodiscover_tasks()

# Scheduled tasks with celery beat
app.conf.beat_schedule = {
    # Executes everyday at 2:00AM
    'delete-read-everyday': {
        'task': 'trackapp.tasks.delete_read_notifications',
        'schedule': crontab(hour=2, minute=0),
    },
}
```

Tasks.py:
```python
from __future__ import absolute_import, unicode_literals
from <myproject>.celery import app
from django.urls import reverse
from django.utils import timezone

@app.task
def delete_read_notifications():
    from <myapp>.models import Notification
    from django.conf import settings
    curr_date = timezone.now()  # timezone-aware current time
    notifications = Notification.objects.all()
    for notification in notifications:
        if notification.is_read:
            delta = curr_date - notification.time_opened
            if (delta.days > settings.NOTIFICATION_KEEP_WINDOW):
                notification.delete()
```

**Comment by maciej-gol** [comment]
I'm afraid that such support is currently out of scope for this package, as I would like it to do one thing and do it well. As a workaround, I suggest creating a wrapper task that you hook into your celery beat that would then trigger all the other tasks with proper schema:

```python
from django_tenants.utils import get_tenant_model, tenant_context
from django_tenant_schemas.utils import get_tenant_model, tenant_context

@app.task
def delete_read_notifications_in_all_schemas():
    for model in get_tenant_model().objects.all():
        with tenant_context(model):
            delete_read_notifications.delay()
```

That way you can use any package that provides multi-tenancy via postgresql schemas and still benefit from setting the schema in celery tasks provided by this package.

**Comment by b1tst0rm** [comment]
Hi - thanks for the support on this. I do believe what you provided is absolutely an acceptable solution and makes sense from a programmatic standpoint. I was able to get your code working with one minor tweak, which I want to provide below in case others run into the same issue.

```python
@app.task
def delete_read_notifications_in_all_schemas():
    # Exclude public schema in the for loop or else the db query fails due to
    # <appname>_Notification table not existing (obviously it shouldn't if it is not shared to public)
    for model in get_tenant_model().objects.exclude(schema_name='public'):
        with tenant_context(model):
            delete_read_notifications.delay()
```

Besides that, I agree that this shouldn't be integrated with your library and as such I think this issue can be considered closed. Thank you again for the library and supporting it!

**Comment by maciej-gol** [comment]
Will add the solution to readme for future reference .

**Comment by maciej-gol** [comment]
I've just updated the README to cover celery beat integration with an example similar to the above. Thanks guys!

**Comment by mcroni** [comment]
please upgrade the package on pypi

**Comment by maciej-gol** [comment]
@mcroni there was no new code added, so no need to update pypi.
