### ISSUE TITLE
switch_schemas() executes query everytime on tenant object

### ISSUE THREAD

**Issue by kapilrupavatiya** [maciej-gol/tenant-schemas-celery#28]
switch_schemas() is called every time when task is executed. There is one query to get tenant object which is executed every time when we call this function. After getting that tenant object we are setting  tenant in to the connection. 

`tenant = get_tenant_model().objects.get(schema_name=schema)`
`connection.set_tenant(tenant, include_public=True)`

We are generating around 500k tasks every day from around 500 different tenants, So this actually executes 500k queries every day which results in database server load.

But ideally we didn't need tenant object to, We have schema_name here and directly set schema in connection using schema_name. It is possible to avoid this query using below solution?

`connection.set_schema(schema, include_public=True)`

If this solution is not accurate then what is the possible work around for this issue?

We are using below packages:
django-tenant-schemas==1.9.0
tenant-schemas-celery==0.1.7
celery==4.3.0
Django==1.11.17

**Comment by maciej-gol** [comment]
`connection.set_tenant(tenant, include_public=True)` sets the `connection.tenant` attribute, too. On the other hand, `set_schema` uses a `FakeTenant` object instead.

This could lead to very weird behavior that accessing `connection.tenant` doesn't give you an instance of your class.

I'm thinking about creating another task, or adding an optional argument `app.task(raw_schema_name=True)` that would trigger this behavior.

Do you have any other ideas?

**Comment by kapilrupavatiya** [comment]
@maciej-gol Thanks for quick response. We really appreciate your valuable feedback.

I think we can add an optional argument `app.task(tenant_cache_seconds=0)` that will cache tenant object for specified amount of time(seconds). If there is no seconds passed then we didn't need to cache tenant object.

So In switch_schemas() if tenant_cache_seconds is passes then first need to check tenant_object from cache and if not found then get object, set in cache and then return so that from next time it will return from cache and if we found it from cache then return object from cache.

**Comment by maciej-gol** [comment]
Fix on master

**Comment by awaazde** [comment]
@maciej-gol Thanks so much for this fix!

After studying the implementation, it seems that the hook for enabling the cache (setting `tenant_cache_seconds` in the task decorator) is not working.

It doesn't look like this param is taken into the task init and actually overrides the default value of `tenant_cache_seconds=0`.

The test case works by subclassing the TenantTask class, which would work, but the decorator param doesn't seem to affect anything.

Can you check this?

**Comment by awaazde** [comment]
Also, ideally we wouldn't have to enable caching on a task by task basis but instead could set it as a global param.

Caching of the tenant object seems to be more of an all or nothing benefit. Some tasks caching and others seems to defeat the purpose.

So can we make this a global setting that can apply to all tasks?

**Comment by awaazde** [comment]
> @maciej-gol Thanks so much for this fix!
> 
> After studying the implementation, it seems that the hook for enabling the cache (setting `tenant_cache_seconds` in the task decorator) is not working.
> 
> It doesn't look like this param is taken into the task init and actually overrides the default value of `tenant_cache_seconds=0`.
> 
> The test case works by subclassing the TenantTask class, which would work, but the decorator param doesn't seem to affect anything.
> 
> Can you check this?

NM looks like the decorator params are getting picked up deeper in celery lib. Disregard this comment

**Comment by maciej-gol** [comment]
Thanks! Will look into enabling it globally. Most likely via reusing how
celery is getting its configuration. That way I don't need to Come up with
yet another way of configuring things.

pon., 4 maj 2020, 11:50 użytkownik Awaaz.De <notifications@github.com>
napisał:

**Comment by awaazde** [comment]
@maciej-gol check my PR: https://github.com/maciej-gol/tenant-schemas-celery/pull/38
