### ISSUE TITLE
support for `send_task`

### ISSUE THREAD

**Issue by thismatters** [maciej-gol/tenant-schemas-celery#30]
Hello, and thank you for your work!

Our codebase generally prefers to use `celery_app.send_task("task_name")` instead of `task_name.delay()`, however it seems that `tenant-schemas-celery` only supports the latter. Is this intentional? Can the desired behavior be achieved using `send_task` directly?

**Comment by maciej-gol** [comment]
Hey!

I've checked what `send_task` does and, in fact, `apply_async` is using `app.send_task` itself. It shouldn't be a lot of work to implement the change, as we can just move the `apply_async` logic down to `send_task` instead.

I just need to confirm `send_task` is the thing in recent Celery versions.

**Comment by thismatters** [comment]
I've updated to using `delay`, it works just as well for what we are doing! The only reason we _actually_ use `send_task` is when we're sending a task to a different queue (possibly on a different redis instance), and that isn't needed when dealing with the `tenant_context` loops in my project.

**Comment by maciej-gol** [comment]
So you no longer need the change?

pt., 6 mar 2020 o 20:01 Paul Stiverson <notifications@github.com>
napisał(a):

**Comment by thismatters** [comment]
No, it is not needed.

**Comment by maciej-gol** [comment]
Thanks! Closing, then.

**Comment by thismatters** [comment]
I'm sorry to flip-flop like this, but I've encountered a case where `send_task` does make much more sense (so as to avoid circular import issues). Is it reasonable to ask that this be reopened?

**Comment by maciej-gol** [comment]
No problem! Will look into this.

pon., 9 mar 2020 o 21:44 Paul Stiverson <notifications@github.com>
napisał(a):

**Comment by thismatters** [comment]
Thank you!

**Comment by maciej-gol** [comment]
Can you just please tell me which version of Python are you using?

śr., 11 mar 2020 o 23:04 Paul Stiverson <notifications@github.com>
napisał(a):

**Comment by thismatters** [comment]
3.7.4
