### ISSUE TITLE
is this a shared or tenant app for django-tenant-schema?

### ISSUE THREAD

**Issue by tylerecouture** [maciej-gol/tenant-schemas-celery#31]
Hi! Thanks for this app.  I'm trying to integrate it into my project.

Do I put `tenant_schemas_celery` in SHARED_APPS or TENANT_APPS (using django-tenant-schema)

Thanks!

**Comment by maciej-gol** [comment]
You shouldn't need to put `tenant_schemas_celery` in any of these, because this app is not using any models.

**Comment by tylerecouture** [comment]
Thanks!
