### ISSUE TITLE
passing _schema_name kwarg via beat PeriodicTask

### ISSUE THREAD

**Issue by tylerecouture** [maciej-gol/tenant-schemas-celery#34]
Is there a way to pass the _schema_name kwarg into a PeriodicTask who's task is a TenantTask?

For example:

``` python
   from django.db import connection
   from myproject.celery import app

   @app.task
   def my_task():
      print(connection.schema_name)
```

How can insert I the `_schmea_name` kwarg that TenantTask will be looking for into a PeriodicTask from [django-celery-beat](https://pypi.org/project/django-celery-beat/)?

If I try something like this:

``` python
import json
from django.db import connection

PeriodicTask.objects.create(
   interval=schedule,                                     
   name='Testing schemas with beat',     
   task='myapp.tasks.my_task',                    
   args=json.dumps([]), 
   kwargs=json.dumps({
        '_schema_name': connection.schema_name, 
  }),
)
```

I get the error:
`my_task() got an unexpected keyword argument '_schema_name'`

**Comment by maciej-gol** [comment]
Interesting! Will have a look into it, although I don't think it should
break like that.

pt., 17 kwi 2020, 01:56 użytkownik tylerecouture <notifications@github.com>
napisał:

**Comment by tylerecouture** [comment]
Fiddle with this some more, I was putting it in the wrong spot!

Tried this and it worked! Very cool.  Any tips on how to create a mixin to inject this into all the celery-beat models?

``` python
import json
from django.db import connection

PeriodicTask.objects.create(
   interval=schedule,                                     
   name='Testing schemas with beat',     
   task='myapp.tasks.my_task',                    
   args=json.dumps([]), 
   headers=json.dumps({
        '_schema_name': connection.schema_name, 
  }),
)
```

**Comment by maciej-gol** [comment]
What is your celery version? The error `my_task() got an unexpected keyword argument '_schema_name'` looks like the schema name was passed via an argument which is a `Celery<4` behavior.

**Comment by tylerecouture** [comment]
`celery==4.4.2`

**Comment by maciej-gol** [comment]
Do you want to run specific tasks for specific schemas, or for all of the schemas?

**Comment by tylerecouture** [comment]
I am using it to run tasks on specific schemas (which I got working, not sure if you saw that)

**Comment by maciej-gol** [comment]
Yes, it looks like the only reasonable way, sorry.

pt., 1 maj 2020, 18:05 użytkownik tylerecouture <notifications@github.com>
napisał:

**Comment by sabarinathjv** [comment]
i need celery to look on private schema instead of public schema kindly help

**Comment by maciej-gol** [comment]
What do you mean by a private schema? This tool will regard less of the
schema name. Its up to you to configure the name.

sob., 24 kwi 2021, 21:48 użytkownik sabarinathjv ***@***.***>
napisał:
