### ISSUE TITLE
Issues with sentry's headers 

### ISSUE THREAD

**Issue by domdinicola** [maciej-gol/tenant-schemas-celery#46]
Hi there!

I'm having issues with tenant-schemas-celery and sentry!

Troubleshooting in app.py / get_schema_name_from_task.
When getting the task_headers https://github.com/maciej-gol/tenant-schemas-celery/blob/master/tenant_schemas_celery/app.py#L21
it gets me task.request.headers --> {'sentry-trace': 'trace-code'}
instead of task.request where schema information are located!
how do you suggest to approach this? @maciej-gol 
maybe merge those?

thanks in advance!

**Comment by maciej-gol** [comment]
Should've been fixed in `1.0.1`
