### ISSUE TITLE
tenant-schemas-celery with beat

### ISSUE THREAD

**Issue by DigiBrainLLC** [maciej-gol/tenant-schemas-celery#50]
Hi. 

I have a multi-tenant app which needs dynamic periodic scheduling (e.g. a user should be able to create a scheduled test to be sent out periodically... weekly/monthly/etc..) and am having trouble finding the correct solution to the problem so I thought I would ask here.

I already have `tenant-schemas-celery` running in my app and have tried to add `django-tenants-celery-beat`. The problem I have is finding a way for a user to be able to set the scheduled task. 

The first solution I had was to set a scheduled task for each frequency (weeks/months/quarterly/etc), where the task would check the database for a model with a field which contains a date for specific actions (e.g. `activation_date = models.DateTimeField()`) . I then ran into the problem that I don't have access to `request` objects in a scheduled task to look up the tests which are scheduled to begin. 

I am wondering if you have any suggestions on how I could accomplish this using `tenant-schemas` and `tenant-schemas-celery`?

**Comment by maciej-gol** [comment]
Have you solved your issue? Would be great to share, if possible, how so
that future issues can be solved easier :)

wt., 10 sie 2021 o 00:07 DigiBrain LLC ***@***.***>
napisał(a):
