### ISSUE TITLE
Feature request: supporting multiple databases in Celery tasks

### ISSUE THREAD

**Issue by NyanKiyoshi** [maciej-gol/tenant-schemas-celery#52]
This package only set the schema of the default django database, having the support for setting the schema to all databases would be useful for applications spreading the load.

For example having the below-attached settings, the package might want to switch the schema for both connections:
```
DATABASES = {
    'default': {
        'NAME': 'primary_name',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'mysql_user',
        'PASSWORD': 'spam',
    },
    'replica': {
        'NAME': 'replica1_name',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'mysql_user',
        'PASSWORD': 'eggs',
    },
}
```

**Comment by maciej-gol** [comment]
Fixed in version `2.0.0`. Thanks for your contribution!
