### ISSUE TITLE
Celery beat not working as expected

### ISSUE THREAD

**Issue by iamunadike** [maciej-gol/tenant-schemas-celery#55]
I used the approach in the text to set up celery beat for periodic tasks and added the 
CELERY_BEAT_SCHEDULE = {} config to my settings.py but it does not work
However when I switch to normal celery it works

**Comment by maciej-gol** [comment]
What do you mean it doesn't work? The tasks don't get sent by the beat
scheduled? What is your django/celery version?

pon., 27 cze 2022, 12:44 użytkownik Michael You ***@***.***>
napisał:

**Comment by iamunadike** [comment]
django 4.0.2
Celery 5.2.7

Without Beats:
- both works 
- tenant-celery-schema works because I am using django-tenants and this works because it helps the project to be tenant aware
- celery partially works because it can do tenant aware tasks
-
With Background beats or periodic tasks:
- same action with celery but not with tenant aware models because it raises flag of undefined relations since it is not tenant aware
- tenant-schemas-celery does not work at all 
Normal workers work in the background with celery without -B or  beat
but the command 
celery -A <my_app_name> works -B -l info
works if using the default celery config but when I switch the the custom tenant aware one(tenants-schemas-celery) it does not work

**Comment by iamunadike** [comment]
Please am I missing something 
@maciej-gol

**Comment by iamunadike** [comment]
@app.task
def reset_remaining_jobs_in_all_schemas():
    for tenant in get_tenant_model().objects.exclude(schema_name='public'):
        with tenant_context(tenant):
            logger.info("welcome to the multiverse")

the test example does not WORRKKKKKK
