### ISSUE TITLE
I cannot access db datas of any schemas except public from schedule task

### ISSUE THREAD

**Issue by msozkan90** [maciej-gol/tenant-schemas-celery#59]
I have function that wanted to make schedule task. I have 3 different schemas and i want to use this function for all tenant but i can only acces public schema database datas. 
How can i use this function for other tenants ??? or how can i query other tenants database ???
If i do not query from database just using normal function, everything is working fine.
DB=>postgres

####Function#####
 ###   file_case_dates=InsuranceFile.objects.values_list("case_date") ###
### I get error here because this table is not include in public. if i use this function in views or somewhere else is working fine.### 
@app.task(bind=True)
def case_date_check(*args,**kwargs):
    case_date_list=[]  
    file_case_dates=InsuranceFile.objects.values_list("case_date")
    users=User.objects.values_list("username")
    for i in file_case_dates:
        if (i[0] - now).days < 30 and (i[0] - now).days >=0 :
            file=InsuranceFile.objects.filter(case_date=i[0]).values_list("applicant").first()
            case_date_list.append(file)
    for i in users:
        send_review_email(i[0],i[1],case_date_list)
    return True

**Comment by maciej-gol** [comment]
Heya, thanks for raising this!

Do you have a chance to see https://github.com/maciej-gol/tenant-schemas-celery#celery-beat-integration ? It should explain how to run periodic tasks (celery beat) pretty well.
