### ISSUE TITLE
Tasks decorated with worker_ready.connect don't get set to tenant schema

### ISSUE THREAD

**Issue by m4l** [maciej-gol/tenant-schemas-celery#6]
I have a task like this, which I need to run right after the celery worker starts up:

	class OnWorkerReady(TenantTask):
		@worker_ready.connect
		def run(*args, **kwargs):
			Model.objects.all()  # Fails: relation "app_model" does not exist

The db connection schema does not get set to the tenant and db lookups fail, once I remove the decorator and I trigger the task manually it works.

**Comment by maciej-gol** [comment]
Abstracting from whether the schema insertion works or not, are you sure the worker sets the proper schema before dispatching the `worker_ready` signal?
