### ISSUE TITLE
Tests do not succeed due to outdated dependencies

### ISSUE THREAD

**Issue by ZipBrandon** [maciej-gol/tenant-schemas-celery#60]
Hello there. Great project that fills a need! I'm trying to add new functionality on a fork I have and I noticed your tests are failing due to outdated dependencies.

**Comment by maciej-gol** [comment]
Hey!

Extremely sorry for this! Will look into this soon!

Best

czw., 17 lis 2022 o 16:11 Brandon ***@***.***> napisał(a):

**Comment by maciej-gol** [comment]
Dependencies updated! Turned out the regression is with kombu not being up-to-date with the most recent changes to `importlib-metadata`.

The package has been pinned to `<5` until kombu releases their fixes upstream.
