### ISSUE TITLE
Abstract Task class does not work with @shared_task

### ISSUE THREAD

**Issue by cs-satish-mishra** [maciej-gol/tenant-schemas-celery#64]
@maciej-gol I am migrating my existing celery tasks for multitenancy 

```python
class ResultTask(Task):
    abstract = True

    def after_return():
         pass 
 

@shared_task(base=ResultTask, bind=True)
def test(self, data, *args, **kwargs):
     paas 
```

caller: test.apply_async(**args)

it works if I remove base=ResultTask.

**Comment by maciej-gol** [comment]
Thanks for this, will look into it!

**Comment by cs-satish-mishra** [comment]
@maciej-gol Thanks, I figured out that if I instantiate my ResultTask with TenantTask from from tenant_schemas_celery.task import TenantTask it works. May we can document this

**Comment by maciej-gol** [comment]
Added to the README, thanks!
