### ISSUE TITLE
Unable to override the default base Task class for tasks registered without the base option

### ISSUE THREAD

**Issue by sanchit-mathew** [maciej-gol/tenant-schemas-celery#76]
**Context:**
1. We have overridden the `TenantTask` class provided by `tenant-schemas-celery` for our use-case - consider it to be named as `DerivedTenantTask`
2. There exists a task, defined as, for example:
```
@app.task
def my_task(arg1, arg2):
    ...
```

**Issue:**
- `tenant-schemas-celery`'s `CeleryApp.create_task_cls` hardcodes `"tenant_schemas_celery.task:TenantTask"` as the base class that all tasks will be subclassed from
- Due to this, even though we're specifying our custom `DerivedTenantTask` as the base `task_cls` for our celery app, all tasks where the base is not explicity mentioned in the `@app.task` decorator are being subclassed from `tenant-schemas-celery`'s `TenantTask` and due to this, the custom logic we've written in our `DerivedTenantTask` class is not being executed

**Request:**
- Please keep the celery app's `task_cls` attribute in `tenant-schemas-celery`'s `CeleryApp.create_task_cls`:
```
class CeleryApp:
    registry_cls = 'tenant_schemas_celery.registry:TenantTaskRegistry'
    task_cls = "tenant_schemas_celery.task:TenantTask`

    def create_task_cls(self):
        return self.subclass_with_self(
            self.task_cls,
            abstract=True,
            name="TenantTask",
            attribute="_app",
        )
```
- LMK if this was kept intentionally or if you agree that this can be fixed 
- If it can be fixed, also LMK if you're running short on bandwidth and would like me to pick this up myself

**Comment by maciej-gol** [comment]
Thanks for reporting! This indeed looks like an omission. Will look into it!

**Comment by maciej-gol** [comment]
@sanchit-mathew can you please verify if https://github.com/maciej-gol/tenant-schemas-celery/pull/78 this is would work for you?
