### ISSUE TITLE
Support for post switch_schema hooks

### ISSUE THREAD

**Issue by mengchen-yu** [maciej-gol/tenant-schemas-celery#77]
Hi! What is the recommended way to expose the current schema during `task_prerun`?

I'm trying to config error monitoring system (Sentry) prior to task execution with current tenant schema name. 
I see `tenant-schemas-celery` uses `task_prerun` signal. Not aware of a way to specify signal handler priority, I assume I should not just implement another signal processor, as it may get executed before `switch_schema`.

Is there a way for me to get the tenant schema name after `switch_schema` but still before task execution?

**Comment by maciej-gol** [comment]
Hey, Im currently away until next Monday and can't give more elaborate
answer :( There is a function in the library that is used to extract the
schema from the task, you may base off it, but its currently not part of
the public api.

wt., 2 maj 2023, 19:03 użytkownik Mengchen Yu ***@***.***>
napisał:

**Comment by maciej-gol** [comment]
I think the code needs some cleanups from u supported Celery versions. I
will look into it when Im back. By then feel free to use that function

śr., 3 maj 2023, 18:45 użytkownik Mengchen Yu ***@***.***>
napisał:

**Comment by maciej-gol** [comment]
@mengchen-yu I've read that function and you can freely use it for your use case. Its not part of the private API.
