### ISSUE TITLE
Celery beat command

### ISSUE THREAD

**Issue by hpatel1** [maciej-gol/tenant-schemas-celery#9]
> manage.py tenant_command celery --beat **** --schema=tenant1

Given command will run for specified schema.
But I want to run command which can query for periodic tasks to each tenant.

**Comment by maciej-gol** [comment]
You can simply write a `for_each_tenant` task that will take a task name and args, and iterate over all tenants in your app and task of given name with given args.

Something along these lines:

```python
@app.task
def for_each_tenant(task_name, *args, **kwargs):
    schemas = get_all_schemas()
    task = app.tasks[task_name]
    for schema in schemas:
        with django_tenant_schemas.utils.schema_context(schema):
            task.apply_async(*args, **kwargs)
```
